title: "AI Math Notes by Jemima"
description: "Breakdowns of the math behind AI/ML/DL models."
theme: minima

url: "https://Jemimahh.github.io"  # <-- replace with your GitHub username
author: "Jemima Egwurube"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/Jemimahh" }
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/YOUR-LINKEDIN" }

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
